name: CI

on:
  push:
    branches: [master]
    tags: ["jq-*"]
  pull_request:

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - armel
          - armhf
          - i386
          - mips
          - mips64
          - mips64el
          - mipsel
          - ppc64el
          - riscv64
          - s390x
          - win-arm64
        include:
          - arch: amd64
            CC: x86_64-linux-gnu
          - arch: arm64
            CC: aarch64-linux-gnu
          - arch: armel
            CC: arm-linux-gnueabi
          - arch: armhf
            CC: arm-linux-gnueabihf
          - arch: i386
            CC: i686-linux-gnu
          - arch: mips
            CC: mips-linux-gnu
          - arch: mips64
            CC: mips64-linux-gnuabi64
          - arch: mips64el
            CC: mips64el-linux-gnuabi64
          - arch: mipsel
            CC: mipsel-linux-gnu
          - arch: ppc64el
            CC: powerpc64le-linux-gnu
          - arch: riscv64
            CC: riscv64-linux-gnu
          - arch: s390x
            CC: s390x-linux-gnu
          - arch: win-arm64
            CC: aarch64-w64-mingw32

    runs-on: ${{ matrix.arch == 'i386' && 'ubuntu-22.04' || 'ubuntu-24.04' }}

    env:
      AR: ${{ matrix.CC }}-ar
      CC: ${{ matrix.CC }}-gcc
      CPP: ${{ matrix.CC }}-cpp
      LDFLAGS: -s

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            automake autoconf libtool \
            crossbuild-essential-${{ matrix.arch }} \
            ${{ matrix.arch == 'win-arm64' && 'gcc-aarch64-w64-mingw32' || '' }}

      - name: Build
        run: |
          autoreconf -i

          if [ "${{ matrix.arch }}" = "win-arm64" ]; then
            HOST=aarch64-w64-mingw32
            OUTPUT=jq-windows-arm64.exe
          else
            HOST=${{ matrix.CC }}
            OUTPUT=jq-linux-${{ matrix.arch }}
          fi

          ./configure \
            --host=$HOST \
            --disable-docs \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static \
            CFLAGS="-O2 -pthread -fstack-protector-all"

          make -j$(nproc)

          if [ "${{ matrix.arch }}" = "win-arm64" ]; then
            cp jq.exe $OUTPUT
          else
            cp jq $OUTPUT
          fi

      - name: Test
        if: matrix.arch == 'amd64'
        run: |
          make check VERBOSE=yes
          git diff --exit-code

      - uses: actions/upload-artifact@v7
        with:
          name: jq-${{ matrix.arch }}
          path: |
            jq-linux-*
            jq-windows-arm64.exe

  macos:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            target: x86_64-apple-darwin
          - arch: arm64
            target: arm64-apple-darwin

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - run: |
          brew update || brew update-reset
          brew install autoconf automake libtool

      - run: echo "CC=clang -target ${{ matrix.target }}" >> $GITHUB_ENV

      - run: |
          autoreconf -i
          ./configure \
            --host=${{ matrix.target }} \
            --disable-docs \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static

          make -j$(sysctl -n hw.logicalcpu)
          strip jq
          cp jq jq-macos-${{ matrix.arch }}

      - uses: actions/upload-artifact@v7
        with:
          name: jq-macos-${{ matrix.arch }}
          path: jq-macos-${{ matrix.arch }}

  windows:
    strategy:
      matrix:
        arch: [amd64, i386]
        include:
          - arch: amd64
            msystem: UCRT64
            os: windows-2022
          - arch: i386
            msystem: MINGW32
            os: windows-2022

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.msystem }}
          install: base-devel git autoconf automake libtool
          pacboy: toolchain:p

      - run: |
          autoreconf -i
          ./configure \
            --disable-docs \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static

          make -j$(nproc)
          cp jq.exe jq-windows-${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v7
        with:
          name: jq-windows-${{ matrix.arch }}
          path: jq-windows-${{ matrix.arch }}.exe
