  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - armel
          - armhf
          - i386
          - mips
          - mips64
          - mips64el
          - mips64r6
          - mips64r6el
          - mipsel
          - mipsr6
          - mipsr6el
          - powerpc
          - ppc64el
          - riscv64
          - s390x
          - win-arm64
        include:
          - arch: amd64
            CC: x86_64-linux-gnu
          - arch: arm64
            CC: aarch64-linux-gnu
          - arch: armel
            CC: arm-linux-gnueabi
          - arch: armhf
            CC: arm-linux-gnueabihf
          - arch: i386
            CC: i686-linux-gnu
          - arch: mips
            CC: mips-linux-gnu
          - arch: mips64
            CC: mips64-linux-gnuabi64
          - arch: mips64el
            CC: mips64el-linux-gnuabi64
          - arch: mips64r6
            CC: mipsisa64r6-linux-gnuabi64
          - arch: mips64r6el
            CC: mipsisa64r6el-linux-gnuabi64
          - arch: mipsel
            CC: mipsel-linux-gnu
          - arch: mipsr6
            CC: mipsisa32r6-linux-gnu
          - arch: mipsr6el
            CC: mipsisa32r6el-linux-gnu
          - arch: powerpc
            CC: powerpc-linux-gnu
          - arch: ppc64el
            CC: powerpc64le-linux-gnu
          - arch: riscv64
            CC: riscv64-linux-gnu
          - arch: s390x
            CC: s390x-linux-gnu
          - arch: win-arm64
            CC: aarch64-w64-mingw32

    runs-on: ${{ matrix.arch == 'i386' && 'ubuntu-22.04' || 'ubuntu-24.04' }}

    env:
      AR: ${{ matrix.CC }}-ar
      CHOST: ${{ matrix.CC }}
      CC: ${{ matrix.CC }}-gcc
      CPP: ${{ matrix.CC }}-cpp
      LDFLAGS: -s

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            automake autoconf libtool \
            crossbuild-essential-${{ matrix.arch }} \
            ${{ matrix.arch == 'win-arm64' && 'gcc-aarch64-w64-mingw32' || '' }}

      - name: Build
        run: |
          autoreconf -i

          if [ "${{ matrix.arch }}" = "win-arm64" ]; then
            HOST=aarch64-w64-mingw32
            OUTPUT=jq-windows-arm64.exe
          else
            HOST=${{ matrix.CC }}
            OUTPUT=jq-linux-${{ matrix.arch }}
          fi

          ./configure \
            --host=$HOST \
            --disable-docs \
            --with-oniguruma=builtin \
            --enable-static \
            --enable-all-static \
            CFLAGS="-O2 -pthread -fstack-protector-all"

          make -j"$(nproc)"

          if [ "${{ matrix.arch }}" = "win-arm64" ]; then
            cp ./jq.exe $OUTPUT
          else
            cp ./jq $OUTPUT
          fi

      - name: Test
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          make check VERBOSE=yes
          git diff --exit-code

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: jq-${{ matrix.arch }}
          path: |
            jq-linux-*
            jq-windows-arm64.exe
          if-no-files-found: error
          retention-days: 7
